name: Run the Julia Package Butler

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/6 * * * *'

jobs:
  butler:
    name: "Run PkgButler.jl"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
      - uses: davidanthoff/julia-pkgbutler@releases/v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
